disabled_rules: # Rule identifiers to exclude from running
  - trailing_whitespace
  - unused_closure_parameter
  - cyclomatic_complexity

opt_in_rules: # Some rules are provided as opt-in
  - empty_count
  - empty_string
  - redundant_string_enum_value

# All available rules can be checked with the swiftlint rules command
included: # File paths to include in the lint process. If this exists, `--path` is ignored
excluded: # File paths to ignore in the lint process. Has higher priority than `included`
  - Pods
# Configurable rules can be customized in this configuration file
# Rules that trigger either a warning or an error can have their violation level set
force_cast: warning # Implicitly specified
force_try:
  severity: warning # Explicitly specified
# For rules that have both warning and error, if only one value is specified, it's implicitly set to warning level
line_length:
  warning: 110
  ignores_comments: true
# function_body_length:
#  - 25 # warning
#  - 40 # error
# Values can be listed to implicitly specify both sides
type_body_length:
  - 300 # warning
  - 400 # error
# Both can be specified explicitly as well
file_length:
  warning: 500
  error: 1200
# Naming rules can set min_length and max_length for both warning/error
# You can set names to exclude
type_name:
  min_length: 4 # Only applied to warning
  max_length: # Applied to both warning and error
    warning: 40
    error: 50
  excluded:
    - iPhone # Use string value to exclude
  allowed_symbols: ["_"]
identifier_name:
  min_length: # For min_length
    error: 4 # Only apply error
  excluded: # Use a list of strings to exclude
    - id
    - URL
    - url
    - GlobalAPIKey
    - end
    - vm
  allowed_symbols: ["_"]
reporter: "xcode" # Report type (xcode, json, csv, codeclimate, checkstyle, junit, html, emoji, sonarqube, markdown, github-actions-logging)

